dateSite/urls.py
# dateSite/urls.py
from django.conf.urls import url
from . import views
from .autocomplete import *
from django.contrib.auth.decorators import login_required

from .sending import send_mail

# We are adding a URL called /home
app_name = 'dateSite'
urlpatterns = [
    url(r'^$',
        login_required(views.Index.as_view()),
        name='main'),
    url(r'^login/',
        views.LoginView.as_view(),
        name='login',
        kwargs={'redirect_authenticated_user': True}),
    url(r'^online/$',
        views.OnlineMembers.as_view(),
        name='online_members'),
    url(r'^alerts/',
        login_required(views.AlertView.as_view()),
        name='alert'),
    url(r'^logout/',
        login_required(views.LogoutView.as_view()),
        name='logout'),
    url(r'^signup/',
        views.SignupView.as_view(),
        name='signup'),
    url(r'^email/$',
        views.EmailView.as_view(),
        name="account_email"),
    url(r'^contact/$',
        views.contact_form,
        name='contact'),
    url(r'^forbidden/$',
        views.forbidden,
        name='forbidden'),
    url(r'^under_construction/$',
        views.under_construction,
        name='under_construction'),
    url(r'^inbox/(?P<slug>\w*)/$',
        login_required(views.InboxView.as_view()),
        name='inbox'),
    url(r'^myinbox/$',
        login_required(views.InboxView.as_view()),
        name='myinbox'),
    url(r'^(?P<slug>\w+)/$',
        login_required(views.ProfileView.as_view()),
        name='profile'),
    # autocomplete fields
    url(r'^occupation-autocomplete/$',
        OccupationAutocomplete.as_view(),
        name='occupation_autocomplete'),
    url(r'^hobbies-autocomplete/$',
        HobbiesAutocomplete.as_view(),
        name='hobbies_autocomplete'),
    url(r'^pets-autocomplete/$',
        PetsAutocomplete.as_view(),
        name='pets_autocomplete'),
    url(r'^country-autocomplete/$',
        CountryAutocomplete.as_view(),
        name='country_autocomplete'),
    url(r'^edit/(?P<slug>[\-\w]+)/$',
        login_required(views.UpdateProfileView.as_view()),
        name='edit_profile'),
    url(r'^password/reset/$',
        views.PasswordResetView.as_view(),
        name='account_reset_password'),
    # ajax_calls
    url(r'^ajax/clients/',
        views.ajax_clients,
        name='client_list'),
    url(r'^ajax/infogirl/',
        login_required(views.ajax_info_complete_client),
        name='info_complete_client'),
    url(r'^ajax/feeling/$',
        login_required(views.ajax_feeling),
        name='change_feeling'),
    url(r'^ajax/messages/$',
        login_required(views.ajax_room),
        name='my_room'),
    url(r'^ajax/leaveconversation/$',
        login_required(views.leave_conversation),
        name='leaveconversation'),
    url(r'^ajax/notifications/$',
        login_required(views.ajax_notifications),
        name='notifications'),
    url(r'^ajax/checkReadMessage/$',
        login_required(views.ajax_check_readmessage),
        name='read_message'),
    url(r'^ajax/create/album',
        login_required(views.ajax_create_album),
        name='create_album'),
    url(r'^ajax/album/name',
        login_required(views.ajax_change_album_name),
        name='album_name'),
    url(r'^ajax/list_chat/$',
        login_required(views.ajax_list_chat),
        name='list_chat'),
    url(r'^ajax/update/noti/$',
        login_required(views.ajax_readnoti),
        name='read_notifications'),
    url(r'^ajax/qty/noti/$',
        login_required(views.ajax_qtynoti),
        name='qty_notifications'),
    url(r'^ajax/profile/picture$',
        login_required(views.ajax_profile_picture),
        name='profile_picture'),
    url(r'^ajax/save/uploadedpicture$',
        login_required(views.ajax_save_uploadedpicture),
        name='save_profile_picture'),
    url(r'^ajax/delete/uploadedpicture$',
        login_required(views.ajax_delete_uploadedpicture),
        name='save_profile_picture'),
    url(r'^ajax/get/album$',
        login_required(views.ajax_get_album),
        name='get_album'),
    url(r'^ajax/get/albums$',
        login_required(views.ajax_get_albums),
        name='get_albums'),
    url(r'^ajax/list/inbox/$',
        login_required(views.ajax_list_inbox),
        name='list_inbox'),
    url(r'^ajax/get/inbox/$',
        login_required(views.ajax_get_inbox),
        name='get_inbox'),
    url(r'^ajax/get/not_read_inbox/$',
        login_required(views.ajax_not_read_inbox),
        name='not_read_inbox'),
    url(r'^ajax/send/inbox/$',
        login_required(views.ajax_send_inbox),
        name='send_inbox'),
    url(r'^ajax/qty/inbox/$',
        login_required(views.ajax_qtyinbox),
        name='qty_inbox'),
    url(r'^ajax/set_read/inbox/$',
        login_required(views.ajax_set_read_inbox),
        name='set_read_inbox'),
    url(r'^ajax/add/private',
        login_required(views.ajax_add_private_album),
        name='add_private_album'),
    url(r'^ajax/delete/album',
        login_required(views.ajax_delete_album),
        name='delete_album'),
    url(r'^ajax/delete/picture',
        login_required(views.ajax_delete_picture),
        name='delete_picture'),
    url(r'^ajax/add/picture/description',
        login_required(views.ajax_add_picture_description),
        name='add_picture_description'),
    # info views
    url(r'^payments',
        views.payment_proccess,
        name='payment'),
    url(r'^about',
        views.about_view,
        name='about'),
    url(r'^faq',
        views.faq_view,
        name='faq'),
    url(r'^terms',
        views.terms_view,
        name='terms'),
    url(r'^policy',
        views.privacy_view,
        name='policy'),
    url(r'^securely',
        views.securely_view,
        name='securely'),
    url(r'^contactus',
        views.contact_view,
        name='contactus'),
    url(r'^verified',
        views.verified_view,
        name='verified'),

]

dating/urls.py
""" Dating URL Configuration
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
"""

# dating/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views
from django.conf.urls import handler404
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('landings.urls')),
    url(r'', include('manager.urls')),
    url(r'', include('dateSite.urls')),
    url(r'', include('allauth.urls')),
    # files upload
    url(r'^upload/', include('django_file_form.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from . import views


app_name = 'manager'
urlpatterns = [
    url(r'^manager/$',
        views.IndexManager.as_view(),
        name='manager_index'),
    url(r'^manager/login$',
        views.LoginManager.as_view(),
        name='manager_login'),
    url(r'^manager/checkpoint$',
        views.CheckpointManager.as_view(),
        name='manager_checkpoint'),
    url(r'^manager/ajaxconnect$',
        login_required(views.ajax_connect),
        name='ajax_connect'),
    url(r'^manager/ajaxreplaceconnection$',
        login_required(views.ajax_replace_connection),
        name='ajax_replaceconnection'),
    url(r'^supervisor$',
        login_required(views.SupervisorView.as_view()),
        name='supervisor_panel'),
    url(r'^supervisor/newsfeed$',
        views.NewsFeedView.as_view(),
        name='supervisor_newsfeed'),
]

manager/forms.py
from django import forms

class LoginForm(forms.Form):
    email = forms.EmailField(label='', required=True,
                             widget=forms.EmailInput(
                                attrs={'class' : 'form-control',
                                       'id' : 'email',
                                       'tabindex' : 1,
                                       'placeholder' : 'email'}))
    password = forms.CharField(label='',required=True,
                               widget=forms.PasswordInput(
                                   attrs={'class' : 'form-control',
                                          'id' : 'password',
                                          'tabindex' : 2,
                                          'placeholder' : 'password'}))
    remember = forms.BooleanField(label='Remember Me', required=False,
                                 widget=forms.CheckboxInput(
                                     attrs={'class' : 'control',
                                            'id' : 'remember',
                                            'tabindex' : 3,}))

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super(LoginForm, self).__init__(*args, **kwargs)

manager/views.py
import json
from .models import Manager
from .helper import register_login
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic.list import ListView
from django.http import JsonResponse
from dateSite.models.client import Client, ManagerClient
from dateSite.models.inbox import Inbox
from dateSite.models.chat import Room, Message
from dateSite.models.purchase import Purchase
from dateSite.models.enum import ClientTypeE
from django.contrib.auth import authenticate, login as auth_login
from dateSite.forms import LoginForm
from dateSite.base_helper import save_log
from channels import Channel
from dating.settings import USERS_PASS
from django.db.models import Count
from django.contrib.auth.models import User



class LoginManager(View):
    template_name = 'manager/login.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'login_form': LoginForm()})

    def post(self, request, *args, **kwargs):
        login_form = LoginForm(request.POST)

        if not login_form.is_valid():
            return render(request, 'manager:manager_login',
                          {'login_form': login_form})
        else:
            email = login_form.cleaned_data['login']
            password = login_form.cleaned_data['password']
            remember = login_form.cleaned_data['remember']
            user = authenticate(email=email, password=password,
                                remember=remember)
            if user is not None:
                client = Client.objects.get(clicode=user.pk)
                if client.tclcode.tclcode == ClientTypeE['supervisor'].value:
                    auth_login(request, user)
                    return redirect('manager:supervisor_panel')
                elif client.tclcode.tclcode == ClientTypeE['manager'].value:
                    auth_login(request, user)
                    return redirect('manager:manager_index')
                else:
                    return render(request, 'manager/login.html',
                                  {'login_form': login_form,
                                   'error': "You don't have permission to "
                                            "access to this content"})

        return render(request, 'manager:manager_login')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_anonymous:
            return redirect('manager:manager_index')
        return super(LoginManager, self).dispatch(
            self.request, *args, **kwargs)


class IndexManager(ListView):
    model = ManagerClient
    context_object_name = 'members'
    template_name = 'manager/index.html'

    def get_queryset(self):
        manager = Manager()
        managed_clients = manager.get_clients_by_manager(
                            self.request.user.pk)
        manager.update_clients_state(self.request.user.pk)

        return managed_clients

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            return redirect('manager:manager_login')
        else:
            client = Client.objects.get(clicode=request.user.pk)
            if client.tclcode.tclcode != ClientTypeE['manager'].value:
                return redirect('dateSite:forbidden')
        return super(IndexManager, self).dispatch(
            self.request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)


class CheckpointManager(ListView):
    model = ManagerClient
    context_object_name = 'managers'
    template_name = 'manager/checkpoint.html'

    def get_queryset(self):
        manager = ManagerClient.objects.filter(
                        clicodegirl=self.request.user.pk)

        return manager

    def post(self, request, *args, **kwargs):
        manager = request.POST.get("manager")
        clients = Client.objects.filter(clicode__in=[manager,
                                                     self.request.user.pk])

        register_login(clients.get(tclcode=ClientTypeE['our_client'].value),
                       clients.get(tclcode=ClientTypeE['manager'].value))

        return redirect('dateSite:main')

    def dispatch(self, request, *args, **kwargs):
        try:
            client = Client.objects.get(clicode=request.user.pk)
            if client.tclcode.tclcode != ClientTypeE['our_client'].value:
                return redirect('dateSite:main')
            else:
                manager = ManagerClient.objects.filter(
                                clicodegirl=self.request.user.pk)
                if manager.count() <= 1:
                    register_login(manager.first().clicodegirl,
                                   manager.first().clicodemanager)
                    return redirect('dateSite:main')
        except Client.DoesNotExist:
            return redirect('dateSite:main')

        return super(CheckpointManager, self).dispatch(
            self.request, *args, **kwargs)


class SupervisorView(View):
    template_name = 'supervisor/activity.html'

    def get(self, request, *args, **kwargs):
        context = {}
        #Get our clients clicode
        our_clients = Client.objects.filter(tclcode=ClientTypeE['our_client'].value).values('clicode')

        #Rooms without answer
        room = Room.objects.filter(roostartdatetime__isnull=True).values('roocode')
        msgs = Message.objects.filter(roocode__in=room,
                                      clicoderecieved__in=our_clients).order_by(
                                      'clicoderecieved','clicodesent').distinct(
                                      'clicoderecieved','clicodesent')
        context['chat'] = msgs

        context['inbox'] = Inbox.objects.filter(
            clicoderecieved__in=our_clients, inbread=False)

        return render(request, self.template_name, context)

    def dispatch(self, request, *args, **kwargs):
        if Client.objects.filter(clicode=request.user.pk).exists():
            client = Client.objects.get(clicode=request.user.pk)
            if client.tclcode.tclcode != ClientTypeE['supervisor'].value:
                return redirect('manager:manager_index')
        return super(SupervisorView, self).dispatch(
            self.request, *args, **kwargs)


class NewsFeedView(ListView):
    model = User
    context_object_name = 'users'
    template_name = 'supervisor/newsfeed.html'


    def get_context_data(self, **kwargs):
        context = super(NewsFeedView, self).get_context_data(**kwargs)
        context['clients'] = Client.objects.all().order_by(
            '-clidatesubscription')[:200]
        context['purchase'] = Purchase.objects.all().order_by(
            '-purdate')[:100]

        return context

    def query_set(self):
        return User.objects.all().order_by(
            '-date_joined')[:200]



def ajax_connect(request):
    data = request.POST.get('data')
    manager = Client.objects.get(clicode=request.user.pk)
    client = json.loads(data)
    client = Client.objects.get(cliusername=client['client'])
    email = client.cliemail
    password = client.clipassword

    user = authenticate(email=email, password=USERS_PASS)

    if user is not None:
        save_log(True, client, manager)
        auth_login(request, user)
        response = '/'

    return JsonResponse({ "data": response }, safe=False)


def ajax_replace_connection(request):
    data = json.loads(request.POST.get('data'))
    client = Client.objects.get(cliusername=data['client'])
    manager = Client.objects.get(cliusername=data['manager'])

    Channel(client.clireplychannel).send(
        {'message': 'Your connection has been replaced',
         'manager': manager})

    user = authenticate(email=email, password=USERS_PASS)

    if user is not None:
        # Guardar el registro del log
        save_log(True, client, manager)
        auth_login(request, user)
        response = '/'

    return JsonResponse({ "data": 'response' }, safe=False)

manager/templates/manager/checkpoint.html
{% extends '_base.html' %}
{% load static from staticfiles %}
{% block title %}Login{% endblock %}
{% load sass_tags %}

{% block linkcss %}
    <link rel="stylesheet" type="text/css" href="{% sass_src 'manager/css/manager.scss' %}">
{% endblock %}
{% block content %}
<div class="center">
    <div class="form-container">
        <h4>Login @{{user}} as:</h4>
        <hr>
        <form class="manager-choice" method="POST">
        {% csrf_token %}
        <div class="radio-btn">
            {% for manager in managers %}
                <input type="radio" name="manager" class="option-input checkbox" value="{{manager.clicodemanager.clicode}}" required />
                <span>{{manager.clicodemanager.cliusername}}</span><br />
            {% endfor %}
        </div>
        <input type="submit" class="btn btn-primary" value="Login"/>
        </form>
    </div>
</div>
{% endblock %}

manager/templates/manager/index.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}
{% load static from staticfiles %}
{% load sass_tags %}


{% block title %}Manage{% endblock %}
{% block linkcss %}
    <link rel="stylesheet" type="text/css" href="{% sass_src 'manager/css/manager.scss' %}">
{% endblock %}
{% block content %}
<div class="center">
    <ul class="profiles-list">
    {% for member in members %}
        <li>
        {% with member.client.clicodegirl.clireplychannel as active %}
            <div class="img-frame">
                {% if member.client.clicodegirl.profile_picture %}
                    <img src="{{ member.client.clicodegirl.profile_picture }}" alt="{{ member.client.clicodegirl }}" class="{%if active%}grayscale{%endif%}" data-tip="tooltip" data-placement="top" title="{%if active%}Login by {{member.log.clicodemanager}}{%else%}Offline{%endif%}" data-toggle="modal" data-target="#modal" data-client="{{ member.client.clicodegirl }}" data-online="{%if active%}true{%endif%}" data-onlineby="{%if active%}{{member.log.clicodemanager}}{%endif%}"/>
                {% else %}
                    <img src="{% static 'dateSite/img/default_profile.png' %}" alt="{{ member.client.clicodegirl }}" data-toggle="modal" data-target="#modal" data-client="{{ member.client.clicodegirl }}"/>
                {% endif %}
            </div>
            <a data-toggle="modal" data-target="#modal" data-client="{{ member.client.clicodegirl }}" data-online="{%if active%}true{%endif%}" data-onlineby="{%if active%}{{member.log.clicodemanager}}{%endif%}">{{ member.client.clicodegirl }}</a>
        {% endwith %}
        </li>
    {% endfor %}
    </ul>
 </div>

 <!-- Modal -->
 <div id="modal" class="modal fade" tabindex="-1" aria-hidden="true">
     <div class="modal-dialog">
         <div class="modal-content">
             <div class="modal-header">
                 <label class="modal-title"></label>
                 <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                     ×
                 </button>
             </div>
             <div class="modal-body">
             </div>
             <div class="modal-footer">
                 <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                 <button type="button" class="btn btn-primary" id="btnYes">Yes</button>
             </div>
         </div>
     </div>
 </div>

{% endblock %}
{% block javascript %}
<script type="text/javascript" src="{% static 'dateSite/js/tether.js' %}"></script>
<script type="text/javascript" src="{% static 'dateSite/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'dateSite/js/DjangoAjax.js' %}"></script>

<script>
var post_url, post_data;
$(function () {
    $('[data-tip="tooltip"]').tooltip()
});

$('#modal').on('show.bs.modal', function (e) {
     var button = $(e.relatedTarget);
     var client = button.data('client');
     var online = button.data('online');
     var onlineby = button.data('onlineby');

     var modal = $(this)
     if(online){
        modal.find('.modal-body').html("@" + client + " is using by " + onlineby + ". <br/> Do you want to proced and login?");
        post_url = "{% url 'manager:ajax_replaceconnection' %}";
        post_data =  {
          'client': client,
          'manager': onlineby
        };
     }
     else{
        modal.find('.modal-body').html("Do you want connect like @" + client + "?");
        post_url = "{% url 'manager:ajax_connect' %}";
        post_data =  {
          'client': client,
        };
     }
});

$('#btnYes').click(function(){
    $.ajax({
        type: "POST",
        url: post_url,
        data: {
            data: JSON.stringify(post_data),
        },
        success: function(data)
        {
            window.location.href = "{% url 'dateSite:main' %}";
        },
    });
});
</script>
{% endblock %}

manager/templates/manager/login.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}
{% load static from staticfiles %}
{% load filters %}
{% block title %}Login{% endblock %}

{% block content %}
<div class="center">
    <div class="form-container">
        <h2>Login</h2>
        <hr>
        {% if error %}
        <div class="alert alert-block alert-error">
            <ul>
                <li>{{error}}</li>
            </ul>
        </div>
        {% endif %}
        <form class="login-form" method="POST" action="{% url 'manager:manager_login' %}">
            {% csrf_token %}
            {% crispy login_form %}
        </form>
    </div>
</div>
{% endblock %}