dateSite/urls.py
# dateSite/urls.py
from django.conf.urls import url
from . import views
from .autocomplete import *
from django.contrib.auth.decorators import login_required

from .sending import send_mail

# We are adding a URL called /home
app_name = 'dateSite'
urlpatterns = [
    url(r'^$',
        login_required(views.Index.as_view()),
        name='main'),
    url(r'^login/',
        views.LoginView.as_view(),
        name='login',
        kwargs={'redirect_authenticated_user': True}),
    url(r'^online/$',
        views.OnlineMembers.as_view(),
        name='online_members'),
    url(r'^alerts/',
        login_required(views.AlertView.as_view()),
        name='alert'),
    url(r'^logout/',
        login_required(views.LogoutView.as_view()),
        name='logout'),
    url(r'^signup/',
        views.SignupView.as_view(),
        name='signup'),
    url(r'^email/$',
        views.EmailView.as_view(),
        name="account_email"),
    url(r'^contact/$',
        views.contact_form,
        name='contact'),
    url(r'^forbidden/$',
        views.forbidden,
        name='forbidden'),
    url(r'^under_construction/$',
        views.under_construction,
        name='under_construction'),
    url(r'^inbox/(?P<slug>\w*)/$',
        login_required(views.InboxView.as_view()),
        name='inbox'),
    url(r'^myinbox/$',
        login_required(views.InboxView.as_view()),
        name='myinbox'),
    url(r'^(?P<slug>\w+)/$',
        login_required(views.ProfileView.as_view()),
        name='profile'),
    # autocomplete fields
    url(r'^occupation-autocomplete/$',
        OccupationAutocomplete.as_view(),
        name='occupation_autocomplete'),
    url(r'^hobbies-autocomplete/$',
        HobbiesAutocomplete.as_view(),
        name='hobbies_autocomplete'),
    url(r'^pets-autocomplete/$',
        PetsAutocomplete.as_view(),
        name='pets_autocomplete'),
    url(r'^country-autocomplete/$',
        CountryAutocomplete.as_view(),
        name='country_autocomplete'),
    url(r'^edit/(?P<slug>[\-\w]+)/$',
        login_required(views.UpdateProfileView.as_view()),
        name='edit_profile'),
    url(r'^password/reset/$',
        views.PasswordResetView.as_view(),
        name='account_reset_password'),
    # ajax_calls
    url(r'^ajax/clients/',
        views.ajax_clients,
        name='client_list'),
    url(r'^ajax/infogirl/',
        login_required(views.ajax_info_complete_client),
        name='info_complete_client'),
    url(r'^ajax/feeling/$',
        login_required(views.ajax_feeling),
        name='change_feeling'),
    url(r'^ajax/messages/$',
        login_required(views.ajax_room),
        name='my_room'),
    url(r'^ajax/leaveconversation/$',
        login_required(views.leave_conversation),
        name='leaveconversation'),
    url(r'^ajax/notifications/$',
        login_required(views.ajax_notifications),
        name='notifications'),
    url(r'^ajax/checkReadMessage/$',
        login_required(views.ajax_check_readmessage),
        name='read_message'),
    url(r'^ajax/create/album',
        login_required(views.ajax_create_album),
        name='create_album'),
    url(r'^ajax/album/name',
        login_required(views.ajax_change_album_name),
        name='album_name'),
    url(r'^ajax/list_chat/$',
        login_required(views.ajax_list_chat),
        name='list_chat'),
    url(r'^ajax/update/noti/$',
        login_required(views.ajax_readnoti),
        name='read_notifications'),
    url(r'^ajax/qty/noti/$',
        login_required(views.ajax_qtynoti),
        name='qty_notifications'),
    url(r'^ajax/profile/picture$',
        login_required(views.ajax_profile_picture),
        name='profile_picture'),
    url(r'^ajax/save/uploadedpicture$',
        login_required(views.ajax_save_uploadedpicture),
        name='save_profile_picture'),
    url(r'^ajax/delete/uploadedpicture$',
        login_required(views.ajax_delete_uploadedpicture),
        name='save_profile_picture'),
    url(r'^ajax/get/album$',
        login_required(views.ajax_get_album),
        name='get_album'),
    url(r'^ajax/get/albums$',
        login_required(views.ajax_get_albums),
        name='get_albums'),
    url(r'^ajax/list/inbox/$',
        login_required(views.ajax_list_inbox),
        name='list_inbox'),
    url(r'^ajax/get/inbox/$',
        login_required(views.ajax_get_inbox),
        name='get_inbox'),
    url(r'^ajax/get/not_read_inbox/$',
        login_required(views.ajax_not_read_inbox),
        name='not_read_inbox'),
    url(r'^ajax/send/inbox/$',
        login_required(views.ajax_send_inbox),
        name='send_inbox'),
    url(r'^ajax/qty/inbox/$',
        login_required(views.ajax_qtyinbox),
        name='qty_inbox'),
    url(r'^ajax/set_read/inbox/$',
        login_required(views.ajax_set_read_inbox),
        name='set_read_inbox'),
    url(r'^ajax/add/private',
        login_required(views.ajax_add_private_album),
        name='add_private_album'),
    url(r'^ajax/delete/album',
        login_required(views.ajax_delete_album),
        name='delete_album'),
    url(r'^ajax/delete/picture',
        login_required(views.ajax_delete_picture),
        name='delete_picture'),
    url(r'^ajax/add/picture/description',
        login_required(views.ajax_add_picture_description),
        name='add_picture_description'),
    # info views
    url(r'^payments',
        views.payment_proccess,
        name='payment'),
    url(r'^about',
        views.about_view,
        name='about'),
    url(r'^faq',
        views.faq_view,
        name='faq'),
    url(r'^terms',
        views.terms_view,
        name='terms'),
    url(r'^policy',
        views.privacy_view,
        name='policy'),
    url(r'^securely',
        views.securely_view,
        name='securely'),
    url(r'^contactus',
        views.contact_view,
        name='contactus'),
    url(r'^verified',
        views.verified_view,
        name='verified'),

]

dating/urls.py
""" Dating URL Configuration
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
"""

# dating/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views
from django.conf.urls import handler404
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('landings.urls')),
    url(r'', include('manager.urls')),
    url(r'', include('dateSite.urls')),
    url(r'', include('allauth.urls')),
    # files upload
    url(r'^upload/', include('django_file_form.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from . import views


app_name = 'manager'
urlpatterns = [
    url(r'^manager/$',
        views.IndexManager.as_view(),
        name='manager_index'),
    url(r'^manager/login$',
        views.LoginManager.as_view(),
        name='manager_login'),
    url(r'^manager/checkpoint$',
        views.CheckpointManager.as_view(),
        name='manager_checkpoint'),
    url(r'^manager/ajaxconnect$',
        login_required(views.ajax_connect),
        name='ajax_connect'),
    url(r'^manager/ajaxreplaceconnection$',
        login_required(views.ajax_replace_connection),
        name='ajax_replaceconnection'),
    url(r'^supervisor$',
        login_required(views.SupervisorView.as_view()),
        name='supervisor_panel'),
    url(r'^supervisor/newsfeed$',
        views.NewsFeedView.as_view(),
        name='supervisor_newsfeed'),
]

dateSite/views.py
import json
import socket, struct
import logging
from ipware.ip import get_ip
from datetime import datetime
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from allauth.account.views import (SignupView, LoginView, LogoutView,
                                   EmailView, PasswordResetView)
from django.views.generic.edit import UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from .models.testimonial import Testimonial
from .models.purchase import Purchase
from .models.client import Client, Picture, PhotoAlbum
from .models.enum import ClientTypeE, SubServiceE
from .models.notification import Notification, NotificationType
from .models.inbox import Inbox
from .models.deniedip import DeniedIp
from .models.log_session import LogSession
from .base_helper import save_log, can_access, get_private_albums
from .forms import EditProfileForm, UploadAlbumForm, UploadFilesForm
from channels import Channel
from .ajax_request import *
from .statics import *


class LoginView(LoginView):
    def __init__(self, **kwargs):
        super(LoginView, self).__init__(*kwargs)

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        client_testimonials = list(Testimonial.objects.filter(
                                testype='C',
                                tesactive=True).order_by(
                                '-tesname')[:6])
        context['client_testimonials'] = client_testimonials
        love_stories = list(Testimonial.objects.filter(
            testype='L',
            tesactive=True).order_by(
            '-tesname')[:6])
        context['love_stories'] = love_stories
        # Cantidad de miembros
        context['total_members'] = Client.total_members()
        context['total_women'] = Client.total_members_by_gender(2)
        context['total_men'] = Client.total_members_by_gender(1)
        context['total_online'] = Client.total_members_online()
        context['ip'] = get_ip(self.request)
        return context

    def form_invalid(self, form):
        return render(self.request, 'account/login.html', {'login_form': form})


class LogoutView(LogoutView):
    from .models.client import ManagerClient
    def __init__(self, **kwargs):
        super(LogoutView, self).__init__(*kwargs)

    def logout(self):
        if Client.objects.filter(clicode=self.request.user.pk).exists():
            client = Client.objects.get(clicode=self.request.user.pk)
            if (client.tclcode.tclcode == ClientTypeE['client'].value or
                    client.tclcode.tclcode == ClientTypeE['supervisor'].value):
                save_log(False, client)
            elif client.tclcode.tclcode == ClientTypeE['manager'].value:
                save_log(False, client, client)
            elif client.tclcode.tclcode == ClientTypeE['our_client'].value:
                previous_log = LogSession.objects.filter(
                        clicode=client, logsignout__isnull=True)
                if previous_log:
                    previous_log = previous_log.latest('logsignin')
                    managed_girls = ManagerClient.objects.filter(
                        clicodemanager=previous_log.clicodemanager).values_list(
                            'clicodegirl', flat=True)
                    online = LogSession.objects.filter(
                        clicode__in=managed_girls, logsignout__isnull=True,
                        clicodemanager=previous_log.clicodemanager).exclude(
                            clicode__in=[client,previous_log.clicodemanager])
                    if not online:
                        save_log(False, previous_log.clicodemanager)
                    save_log(False, client)


        super(LogoutView, self).logout()


class SignupView(SignupView):

    def get_context_data(self, **kwargs):
        context = super(SignupView, self).get_context_data(**kwargs)
        return context

    def form_invalid(self, form):
        return render(self.request,
                      'account/signup.html',
                      {'signup_form': form})


class EmailView(EmailView):

    def __init__(self, **kwargs):
        super(EmailView, self).__init__(*kwargs)


class PasswordResetView(PasswordResetView):
    from django.contrib.auth.models import User

    def __init__(self, **kwargs):
        super(PasswordResetView, self).__init__(*kwargs)

    def dispatch(self, request, *args, **kwargs):
        if Client.objects.filter(clicode=self.request.user.pk).exists():
            if not can_access(self.request.user):
                return redirect("dateSite:forbidden")
        return super(PasswordResetView, self).dispatch(
            self.request, *args, **kwargs)

    def form_valid(self, form):
        if form.is_valid():
            email = form.cleaned_data["email"]
            if not can_access(User.objects.get(email=email)):
                return redirect("dateSite:forbidden")
        return super(PasswordResetView, self).form_valid(form)


class Index(ListView):
    model = Client
    context_object_name = 'members'
    template_name = 'dateSite/main.html'

    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        context['seaminage'] = self.request.POST.get('seaminage', 0)
        context['seamaxage'] = self.request.POST.get('seamaxage', 0)
        context['country'] = self.request.POST.get('seacountry', 0)

        if Client.objects.filter(clicode=self.request.user.pk).exists():
            client = Client.objects.get(clicode=self.request.user.pk)
            context['show_promo_10'] = 1
            if client.tclcode.tclcode == ClientTypeE['client'].value:
                init_promo = datetime(2017, 6, 11, 23, 59, 59)
                if LogSession.objects.filter(
                        clicode=self.request.user.pk,
                        logsignin__gte=init_promo.date()).count() > 1:
                    context['show_promo_10'] = 0
        return context

    def get_queryset(self):
        user = self.request.user
        if Client.objects.filter(clicode=user.pk).exists():  # Es un cliente
            client = Client.objects.get(clicode=user.pk)
            gen_code = client.gencode.genpreference

            if (client.tclcode.tclcode == ClientTypeE['our_client'].value):
                tcl_code = [ClientTypeE['client'].value]
            else:
                tcl_code = [ClientTypeE['client'].value,
                            ClientTypeE['our_client'].value]

            min_age = self.request.POST.get('seaminage')
            max_age = self.request.POST.get('seamaxage')
            country = self.request.POST.get('seacountry')

            all_members = Client.list_client(tcl_code, gen_code, min_age,
                                             max_age, country)
            show_more = 1 if (len(all_members) > 18) else 0
            members = randomize(all_members, 18)
        else:  # Es un usuario
            json_gender = json.loads(user.last_name)
            gender = Gender.objects.get(gencode=json_gender['gen'])
            gen_code = gender.genpreference

            tcl_code = [ClientTypeE['client'].value]
            tcl_code = [ClientTypeE['our_client'].value]

            min_age = self.request.POST.get('seaminage')
            max_age = self.request.POST.get('seamaxage')
            country = self.request.POST.get('seacountry')

            all_members = Client.list_client(tcl_code, gen_code, min_age,
                                             max_age, country)
            show_more = 1 if (len(all_members) > 18) else 0
            members = randomize(all_members, 18)

        result = []
        result.append(members)  # Los miembros
        result.append(show_more)  # Si hay mas

        return result


    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if Client.objects.filter(clicode=request.user.pk).exists():
            client = Client.objects.get(clicode=request.user.pk)
            if client.tclcode.tclcode == ClientTypeE['manager'].value:
                return redirect('manager:manager_index')
        return super(Index, self).dispatch(
            self.request, *args, **kwargs)


class AlertView(ListView):
    model = Notification
    context_object_name = 'all_notifications'
    template_name = 'dateSite/notifications.html'

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        return context

    def get_queryset(self):
        user = self.request.user
        Notification.objects.filter(
            clicoderecieved=user.pk,
            notread=False).update(
            notread=True)
        all_notifications = Notification.objects.filter(
            clicoderecieved=user.pk).order_by("-notcode")
        return all_notifications


class ProfileView(DetailView):
    from django.http import Http404
    from .models.client import ClientCollectionAlbum

    model = Client
    template_name = 'dateSite/profile.html'
    slug_field = 'cliusername'
    context_object_name = 'member'

    def get_context_data(self, **kwargs):
        current_client = kwargs.get('object')
        if not Client.objects.filter(
                clicode=current_client.pk).exists():
            raise Http404

        context = super(ProfileView, self).get_context_data(**kwargs)
        album = PhotoAlbum.objects.filter(clicode=current_client, phatype=1,
                                          phaactive=True).order_by(
                                                    'phacreationdate').first()
        context['album_list'] = get_client_albums(current_client)
        if album:
            public_pictures = Picture.objects.filter(
                picactive=True, phacode=album).exclude(

dateSite/templates/dateSite/approval.html
{% extends './client_base.html' %}
{% load static from staticfiles %}
{% load extra_filters %}
{% load sass_tags %}
{% load crispy_forms_tags %}

{% block linkcss %}
<link rel="stylesheet" type="text/css" href="{% sass_src 'dateSite/css/approval.scss' %}">
{% endblock %}

{% block content %}
<div class="approval row">
    {% if approval.msg %}
    <div class="col-xs-12 app-content">{{ approval.msg }}</div>
    <div class="col-xs-12 app-content">{{ approval.ip }}</div>
    {% else %}
    <div class="col-xs-12 app-msg">Payment Successful</div>
    <div class="col-xs-12 containerbutton"><a href="{% url 'dateSite:main' %}" class="app-button">START TO ENJOY</a></div>
    <div class="col-xs-12 app-content">You bought {{ approval.credits }} credits for USD{{approval.price}}</div>
    <div class="col-xs-12 app-content">{{ approval.ip }}</div>
    {% endif %}
</div>
{% endblock %}

{% block javascript %}
{% endblock %}

dateSite/templates/dateSite/client_list.html
{% load static from staticfiles %}
{% load extra_filters %}

<ul class="client-list">
    {% for member in members.0 %}
    <li id="member_{{member.clicode}}" name="list-members" data-username="{{member.cliusername}}">
        {% if member.profile_picture %}
        <img src="{{ member.profile_picture }}" alt="{{ member.cliusername }}" title="{{ member.cliusername }}" />
        {% else %}
        <img src="{% static 'dateSite/img/default_profile.png' %}" alt="{{ member.cliusername }}" title="{{ member.cliusername }}" />
        {% endif %}
        {% if member.cliverified %}
        <div class="user-verified">
            <img src="{% static 'dateSite/img/user-verified.png' %}" title="Verified member" data-toggle="tooltip" />
        </div>
        {% endif %}
        <div class="profile-info">
            <div class="summary">
                <div class="username">
                    {% if member.age != 0 %}
                        {% if member.cliusername|length < 12 %}
                        @{{ member.cliusername }}, {{ member.age }}
                        {% else %}
                        @{{ member.cliusername|truncatechars:16 }}...
                        {% endif %}
                    {% else %}
                        @{{ member.cliusername }}
                    {% endif %}
                </div>
                <div class="city">
                    {% if member.citcode %}{{ member.citcode|truncatechars:18 }}{% endif %}
                </div>
                <div class="btn-chat">CHAT NOW</div>
            </div>
            <div class="feeling">
                {% if member.feecode %}
                <img src="{% static '' %}dateSite/img/icons/{{ member.feecode.feeiconfile }}" alt="{{ member.feecode.feedescription }}" />
                {% endif %}
            </div>
        </div>
    </li>
    {% empty %}
    <li class="noresults">
        <p class="noresulttitle">NOT RESULTS FOUND</p>
        <p class="noresultmsg">Sorry we dont have any matches to show. Please open the value of the search filters.</p>
    </li>
    {% endfor %}
</ul>

dateSite/templates/dateSite/manager_base.html
{% load static from staticfiles %}
{% load sass_tags %}
{% load i18n %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>DatingLatinos.com</title>
        <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static "dateSite/css/font-awesome.css" %}">
        <link rel="stylesheet" type="text/css" href="{% sass_src "dateSite/css/home_manager.scss" %}">
        <link rel="stylesheet" type="text/css" href="{% sass_src "dateSite/css/menu_manager.scss" %}">
        <link rel="stylesheet" type="text/css" href="{% sass_src "dateSite/css/chat_manager.scss" %}">
        {% block linkcss %}
        {% endblock %}

        <script type="text/javascript" src="{% static 'dateSite/js/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'dateSite/js/tether.js' %}"></script>
        <script type="text/javascript" src="{% static 'dateSite/js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'dateSite/js/jquery.form.js' %}"></script>
        <script type="text/javascript" src="{% static 'dateSite/js/DjangoAjax.js' %}"></script>
    </head>
    <body>
        <nav class="navbar">
            <div class="navbar-back">
                <div class="navbar-header logo-img">
                    <a href="{% url 'dateSite:manager' %}">
                        <div class="navbar-brand">
                        </div>
                    </a>
                </div>
                <div id="menu-items" class="col-xs-12 navbar-toggleable-sm">
                    <div class="row pull-right">
                        {% include "./navbar/menu_manager.html" %}
                    </div>
                </div>
            </div>
        </nav>
        <div class="subpage">
            <section class="container-home">
                {% block content %}
                {% endblock %}
            </section>
        </div>

        <div id="verifiedModal" class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            {% include "account/email_confirmation_modal.html" %}
        </div>
        <script type="text/javascript">
            //Show email confirmation message if user hasn't your email verified
            $(document).ready(function() {
                var client = '{{ is_client }}'
                if(client == 'True'){
                    var verify = '{{ verified }}'

                    if(verify === 'False')
                        $('#verifiedModal').modal('show');
                }
            });
        </script>
        {% block javascript %}
        {% endblock %}
    </body>
</html>

dateSite/templates/dateSite/manager_girls.html
{% extends './public_base.html' %}
{% load static from staticfiles %}
{% load sass_tags %}
{% load extra_filters %}
{% load crispy_forms_tags %}

{% block linkcss %}
    <link rel="stylesheet" type="text/css" href="{% sass_src 'dateSite/css/manager_girls.scss' %}">
{% endblock %}

{% block contentinit %}
{% endblock %}
{% block content %}
<div class="subpage">
    <section class="container-home">
        {% if manager_girls == "NO"%}
        Datos incorrectos!
        {% else %}
        HOLA {{manager_girls}}
        {% endif %}
    </section>
</div>
{% endblock %}
{% block contentend %}
{% endblock %}

{% block javascript %}
{% endblock %}

dateSite/templates/dateSite/mnu.html
{% load static from staticfiles %}
{% load extra_filters %}

<header>
    <div class="logo"></div>
    <ul class="mnu">
        <li class="mnu-search">
            <div class="mnu-text">Search</div>
            <div class="back-icon">
                <div class="mnu-icon"></div>
            </div>
        </li>
        <li class="mnu-feel">
            <div class="mnu-text">I Feel</div>
            <div class="back-icon">
                <div class="img-icon">
                    <img id='feel-icon' src="{% static 'dateSite/img/icons/' %}{{ feel }}"/>
                </div>
            </div>
        </li>
        <li class="mnu-alert">
            <div class="mnu-text">Alerts</div>
            <div class="back-icon">
                <div class="mnu-icon"></div>
                {% if quantity_ntf == 0 %}
                <div id="alertsquantity" class="badget" style="display: none;">{{quantity_ntf}}</div>
                {% elif quantity_ntf < 10 %}
                <div id="alertsquantity" class="badget">{{quantity_ntf}}</div>
                {% else %}
                <div id="alertsquantity" class="badget">+9</div>
                {% endif %}
            </div>
        </li>
        <a href="{% url 'dateSite:myinbox' %}">
            <li class="mnu-inbox">
                <div class="mnu-text">Inbox</div>
                <div class="back-icon">
                    <div class="mnu-icon"></div>
                </div>
            </li>
        </a>
        <li class="mnu-profile">
            <div class="mnu-text">Profile</div>
            {% if profile_picture %}
            <div class="back-icon">
                <img src="{{ profile_picture }}" alt="@{{ username }}" title="@{{ username }}"/>
            </div>
            {% else %}
            <div class="back-icon">
                <div class="mnu-icon"></div>
            </div>
            {% endif %}
        </li>
    </ul>
</header>

{% include "./navbar/search_form_home.html" %}
{% include "./navbar/feeling_form_home.html" %}
{% include "./navbar/alerts_menu_home.html" %}
{% include "./navbar/profile_menu_home.html" %}

dateSite/templates/dateSite/public_base.html
{% load static from staticfiles %}
{% load sass_tags %}
{% load i18n %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="">
        <meta name="keywords" content="Dating site, online dating, free dating sites, online dating sites">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>DatingLatinos.com</title>
        <link rel="shortcut icon" type="image/png" href="{% static 'dateSite/img/favicon.ico' %}"/>
        <link rel="stylesheet" type="text/css" href="{% sass_src 'dateSite/css/login.scss' %}">
        <script type="text/javascript" src="{% static 'dateSite/js/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'dateSite/js/tether.js' %}"></script>
        <script type="text/javascript" src="{% static 'dateSite/js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'dateSite/js/jquery.form.js' %}"></script>
        <script type="text/javascript" src="{% static 'dateSite/js/DjangoAjax.js' %}"></script>
        {% block linkcss %}
        {% endblock %}
    </head>
    <body>
        <nav class="navbar">
            <div class="container">
                <div class="navbar-header logo-img">
                    {% if not user.is_authenticated %}
                    <button class="navbar-toggler hidden-lg-up pull-xs-right btn-padlock" data-toggle="collapse" data-target="#secLogin">
                        <img src="{% static "dateSite/img/signin.png" %}" alt="Login" />
                    </button>
                    {% endif %}
                    <a href="{% url 'dateSite:login' %}">
                        <div class="navbar-brand">
                        </div>
                    </a>
                </div>
                {% if not user.is_authenticated %}
                    <div id="secLogin" class="collapse navbar-toggleable-md" role="search">
                        <span></span>
                        <div class="secLogin">
                            <form class="form-inline pull-md-right clear-md-down" autocomplete="new-password" method="POST" action="{% url 'account_login' %}">
                                <div class="form-label">
                                    {% blocktrans %}
                                    If you have not created an account yet, then please
                                    {% endblocktrans %}
                                    <a href="{% url 'account_signup' %}">sign up</a> first.
                                </div>
                                {% csrf_token %}
                                {% crispy login_form %}
                                {% if redirect_field_value %}
                                    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                                {% endif %}
                            </form>
                        </div>
                    </div>
                {% endif %}
            </div>
        </nav>
                {% block contentinit %}
                {% endblock %}
                {% block content %}
                {% endblock %}
                {% block contentend %}
                {% endblock %}
                <input type="hidden" value="{% static '' %}" id="s3" name="s3" />
                <input type="hidden" value="{{MEDIA_URL}}" id="s3_root" name="s3_root" />
        <footer>
            <div class="container-fluid">
                <div class="container">
                    <div class="row">
                        <nav class="col-xs-12">
                            <ol>
                                <li><a href="{% url 'dateSite:about' %}">About Us</a></li>
                                <li><a href="{% url 'dateSite:securely' %}">Dating Securely</a></li>
                                <li><a href="{% url 'dateSite:verified' %}">Verified Member</a></li>
                                <li><a href="{% url 'dateSite:faq' %}">FAQ</a></li>
                                <li><a href="{% url 'dateSite:contact' %}">Contact Us</a></li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="container-fluid copyrigth">
                <div class="container">
                    <div class="row" role="contentinfo">
                    <span> Copyright DatingLatinos.com. All rights reserved.</span>
                    <span>
                    <a href="{% url 'dateSite:terms' %}">Terms & Conditions</a> |
                    <a href="{% url 'dateSite:policy' %}">Privacy Policy</a>
                    </span>
                    </div>
                </div>
            </div>
        </footer>
        {% block javascript %}
        {% endblock %}
    </body>
</html>