dateSite/urls.py
# dateSite/urls.py
from django.conf.urls import url
from . import views
from .autocomplete import *
from django.contrib.auth.decorators import login_required

from .sending import send_mail

# We are adding a URL called /home
app_name = 'dateSite'
urlpatterns = [
    url(r'^$',
        login_required(views.Index.as_view()),
        name='main'),
    url(r'^login/',
        views.LoginView.as_view(),
        name='login',
        kwargs={'redirect_authenticated_user': True}),
    url(r'^online/$',
        views.OnlineMembers.as_view(),
        name='online_members'),
    url(r'^alerts/',
        login_required(views.AlertView.as_view()),
        name='alert'),
    url(r'^logout/',
        login_required(views.LogoutView.as_view()),
        name='logout'),
    url(r'^signup/',
        views.SignupView.as_view(),
        name='signup'),
    url(r'^email/$',
        views.EmailView.as_view(),
        name="account_email"),
    url(r'^contact/$',
        views.contact_form,
        name='contact'),
    url(r'^forbidden/$',
        views.forbidden,
        name='forbidden'),
    url(r'^under_construction/$',
        views.under_construction,
        name='under_construction'),
    url(r'^inbox/(?P<slug>\w*)/$',
        login_required(views.InboxView.as_view()),
        name='inbox'),
    url(r'^myinbox/$',
        login_required(views.InboxView.as_view()),
        name='myinbox'),
    url(r'^(?P<slug>\w+)/$',
        login_required(views.ProfileView.as_view()),
        name='profile'),
    # autocomplete fields
    url(r'^occupation-autocomplete/$',
        OccupationAutocomplete.as_view(),
        name='occupation_autocomplete'),
    url(r'^hobbies-autocomplete/$',
        HobbiesAutocomplete.as_view(),
        name='hobbies_autocomplete'),
    url(r'^pets-autocomplete/$',
        PetsAutocomplete.as_view(),
        name='pets_autocomplete'),
    url(r'^country-autocomplete/$',
        CountryAutocomplete.as_view(),
        name='country_autocomplete'),
    url(r'^edit/(?P<slug>[\-\w]+)/$',
        login_required(views.UpdateProfileView.as_view()),
        name='edit_profile'),
    url(r'^password/reset/$',
        views.PasswordResetView.as_view(),
        name='account_reset_password'),
    # ajax_calls
    url(r'^ajax/clients/',
        views.ajax_clients,
        name='client_list'),
    url(r'^ajax/infogirl/',
        login_required(views.ajax_info_complete_client),
        name='info_complete_client'),
    url(r'^ajax/feeling/$',
        login_required(views.ajax_feeling),
        name='change_feeling'),
    url(r'^ajax/messages/$',
        login_required(views.ajax_room),
        name='my_room'),
    url(r'^ajax/leaveconversation/$',
        login_required(views.leave_conversation),
        name='leaveconversation'),
    url(r'^ajax/notifications/$',
        login_required(views.ajax_notifications),
        name='notifications'),
    url(r'^ajax/checkReadMessage/$',
        login_required(views.ajax_check_readmessage),
        name='read_message'),
    url(r'^ajax/create/album',
        login_required(views.ajax_create_album),
        name='create_album'),
    url(r'^ajax/album/name',
        login_required(views.ajax_change_album_name),
        name='album_name'),
    url(r'^ajax/list_chat/$',
        login_required(views.ajax_list_chat),
        name='list_chat'),
    url(r'^ajax/update/noti/$',
        login_required(views.ajax_readnoti),
        name='read_notifications'),
    url(r'^ajax/qty/noti/$',
        login_required(views.ajax_qtynoti),
        name='qty_notifications'),
    url(r'^ajax/profile/picture$',
        login_required(views.ajax_profile_picture),
        name='profile_picture'),
    url(r'^ajax/save/uploadedpicture$',
        login_required(views.ajax_save_uploadedpicture),
        name='save_profile_picture'),
    url(r'^ajax/delete/uploadedpicture$',
        login_required(views.ajax_delete_uploadedpicture),
        name='save_profile_picture'),
    url(r'^ajax/get/album$',
        login_required(views.ajax_get_album),
        name='get_album'),
    url(r'^ajax/get/albums$',
        login_required(views.ajax_get_albums),
        name='get_albums'),
    url(r'^ajax/list/inbox/$',
        login_required(views.ajax_list_inbox),
        name='list_inbox'),
    url(r'^ajax/get/inbox/$',
        login_required(views.ajax_get_inbox),
        name='get_inbox'),
    url(r'^ajax/get/not_read_inbox/$',
        login_required(views.ajax_not_read_inbox),
        name='not_read_inbox'),
    url(r'^ajax/send/inbox/$',
        login_required(views.ajax_send_inbox),
        name='send_inbox'),
    url(r'^ajax/qty/inbox/$',
        login_required(views.ajax_qtyinbox),
        name='qty_inbox'),
    url(r'^ajax/set_read/inbox/$',
        login_required(views.ajax_set_read_inbox),
        name='set_read_inbox'),
    url(r'^ajax/add/private',
        login_required(views.ajax_add_private_album),
        name='add_private_album'),
    url(r'^ajax/delete/album',
        login_required(views.ajax_delete_album),
        name='delete_album'),
    url(r'^ajax/delete/picture',
        login_required(views.ajax_delete_picture),
        name='delete_picture'),
    url(r'^ajax/add/picture/description',
        login_required(views.ajax_add_picture_description),
        name='add_picture_description'),
    # info views
    url(r'^payments',
        views.payment_proccess,
        name='payment'),
    url(r'^about',
        views.about_view,
        name='about'),
    url(r'^faq',
        views.faq_view,
        name='faq'),
    url(r'^terms',
        views.terms_view,
        name='terms'),
    url(r'^policy',
        views.privacy_view,
        name='policy'),
    url(r'^securely',
        views.securely_view,
        name='securely'),
    url(r'^contactus',
        views.contact_view,
        name='contactus'),
    url(r'^verified',
        views.verified_view,
        name='verified'),

]

dating/urls.py
""" Dating URL Configuration
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
"""

# dating/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views
from django.conf.urls import handler404
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('landings.urls')),
    url(r'', include('manager.urls')),
    url(r'', include('dateSite.urls')),
    url(r'', include('allauth.urls')),
    # files upload
    url(r'^upload/', include('django_file_form.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dateSite/models/catalog.py
from django.db import models


class Language(models.Model):
    lancode = models.AutoField(primary_key=True)
    lanname = models.CharField(max_length=60)

    def __str__(self):
        return self.lanname

    class Meta:
        managed = True
        db_table = 'language'


class Country(models.Model):
    coucode = models.AutoField('Code', primary_key=True)
    couname = models.CharField('Name', max_length=100)
    couactive = models.BooleanField('Active')
    couorder = models.SmallIntegerField('Order to show country',blank=True,null=True)

    def __str__(self):
        return self.couname

    def natural_key(self):
        return (self.couname)

    class Meta:
        managed = True
        db_table = 'country'
        ordering = ['couorder']


class CountryLanguage(models.Model):
    colcode = models.AutoField(primary_key=True)
    colname = models.CharField(max_length=100)
    coucode = models.ForeignKey(Country, models.DO_NOTHING,
                                db_column='coucode',
                                related_name='countrylang_country')
    lancode = models.ForeignKey(Language, models.DO_NOTHING,
                                db_column='lancode',
                                related_name='countrylang_language')

    def __str__(self):
        return self.colname

    class Meta:
        managed = True
        db_table = 'country_language'


class City(models.Model):
    citcode = models.AutoField('Code', primary_key=True)
    citname = models.CharField('Name', max_length=40)
    citactive = models.BooleanField('Active')
    citorder = models.SmallIntegerField('Order to show city on profile',blank=True,null=True)
    coucode = models.ForeignKey(Country, models.DO_NOTHING,
                                db_column='coucode',
                                related_name='city_country')

    def __str__(self):
        return '%s, %s' % (self.citname, self.coucode)

    def natural_key(self):
        return '%s, %s' % (self.citname, self.coucode.natural_key())

    class Meta:
        managed = True
        db_table = 'city'
        ordering = ['citorder']


class CityLanguage(models.Model):
    cilcode = models.BigAutoField(primary_key=True)
    cilname = models.CharField(max_length=40)
    citcode = models.ForeignKey(City, models.DO_NOTHING,
                                db_column='citcode',
                                related_name='citylang_city')
    lancode = models.ForeignKey(Language, models.DO_NOTHING,
                                db_column='lancode',
                                related_name='citylang_language')

    def __str__(self):
        return self.cilname

    class Meta:
        managed = True
        db_table = 'city_language'


class Education(models.Model):
    educode = models.AutoField(primary_key=True)
    edudescription = models.CharField(max_length=100)
    eduactive = models.BooleanField()

    def __str__(self):
        return self.edudescription

    class Meta:
        managed = True
        db_table = 'education'


class EducationLanguage(models.Model):
    edlcode = models.AutoField(primary_key=True)
    edldescription = models.CharField(max_length=100)
    educode = models.ForeignKey(Education, models.DO_NOTHING,
                                db_column='educode',
                                related_name='educationlang_education')
    lancode = models.ForeignKey(Language, models.DO_NOTHING,
                                db_column='lancode',
                                related_name='educationlang_language')

    def __str__(self):
        return self.edldescription

    class Meta:
        managed = True
        db_table = 'education_language'


class Feeling(models.Model):
    feecode = models.AutoField(primary_key=True)
    feedescription = models.CharField(max_length=80)
    feeiconfile = models.ImageField('Icon', upload_to='feelings')
    feeactive = models.BooleanField()

    def __str__(self):
        return self.feedescription

    def natural_key(self):
        return str(self.feeiconfile)

    class Meta:
        managed = True
        db_table = 'feeling'


class FeelingLanguage(models.Model):
    felcode = models.AutoField(primary_key=True)
    feldescription = models.CharField(max_length=80)
    feecode = models.ForeignKey(Feeling, models.DO_NOTHING,
                                db_column='feecode',
                                related_name='feelinglang_feeling')
    lancode = models.ForeignKey(Language, models.DO_NOTHING,
                                db_column='lancode',
                                related_name='feelinglang_language')

    def __str__(self):
        return self.feldescription

    class Meta:
        managed = True
        db_table = 'feeling_language'


class Ethnicity(models.Model):
    ethcode = models.AutoField(primary_key=True)
    ethname = models.CharField(max_length=200)
    ethactive = models.BooleanField()

    def __str__(self):
        return self.ethname

    class Meta:
        managed = True
        db_table = 'ethnicity'


class EthnicityLanguage(models.Model):
    etlcode = models.AutoField(primary_key=True)
    etlname = models.CharField(max_length=200)
    ethcode = models.ForeignKey(Ethnicity, models.DO_NOTHING,
                                db_column='ethcode',
                                related_name='ethnicitylang_ethnicity')
    lancode = models.ForeignKey(Language, models.DO_NOTHING,
                                db_column='lancode',
                                related_name='ethnicitylang_language')

    def __str__(self):
        return self.etlname

    class Meta:
        managed = True
        db_table = 'ethnicity_language'


class Gender(models.Model):
    gencode = models.AutoField(primary_key=True)
    genname = models.CharField(max_length=100)
    genpreference = models.PositiveSmallIntegerField(default=1, null=False)
    gendescription = models.CharField(max_length=250, blank=True, null=True)
    genactive = models.BooleanField()

    def natural_key(self):
        return self.gendescription

    def __str__(self):
        return self.gendescription

    class Meta:
        managed = True
        db_table = 'gender'


class GenderLanguage(models.Model):
    gelcode = models.AutoField(primary_key=True)
    gelname = models.CharField(max_length=100)
    geldescription = models.CharField(max_length=250, blank=True, null=True)
    gencode = models.ForeignKey(Gender, models.DO_NOTHING,
                                db_column='getcode',
                                related_name='genderlang_gender')
    lancode = models.ForeignKey(Language, models.DO_NOTHING,
                                db_column='lancode',
                                related_name='genderlang_language')

    def __str__(self):
        return self.gelname

    class Meta:
        managed = True
        db_table = 'gender_language'


class Height(models.Model):
    heicode = models.AutoField(primary_key=True)
    heidescription = models.CharField(max_length=100)

    def __str__(self):
        return self.heidescription

    class Meta:
        managed = True
        db_table = 'height'


class Weight(models.Model):
    weicode = models.AutoField(primary_key=True)
    weidescription = models.CharField(max_length=100)

    def __str__(self):
        return self.weidescription

    class Meta:
        managed = True
        db_table = 'weight'


class Income(models.Model):
    inccode = models.AutoField(primary_key=True)
    incmin = models.IntegerField()
    incmax = models.IntegerField()

    def __str__(self):
        return '%d - %d' % (self.incmin, self.incmax)

    class Meta:
        managed = True
        db_table = 'income'


class Marital(models.Model):
    marcode = models.AutoField(primary_key=True)
    marname = models.CharField(max_length=100)
    maractive = models.BooleanField()

    def __str__(self):
        return self.marname

    class Meta:
        managed = True
        db_table = 'marital'


class MaritalLanguage(models.Model):
    malcode = models.AutoField(primary_key=True)
    malname = models.CharField(max_length=100)
    marcode = models.ForeignKey(Marital, models.DO_NOTHING,
                                db_column='marcode',
                                related_name='maritallang_marital')
    lancode = models.ForeignKey(Language, models.DO_NOTHING,
                                db_column='lancode',
                                related_name='maritallang_language')

    def __str__(self):
        return self.malname

    class Meta:
        managed = True
        db_table = 'marital_language'


class Occupation(models.Model):
    ocucode = models.AutoField(primary_key=True)
    ocudescription = models.CharField(max_length=100)
    ocuactive = models.BooleanField()

    def __str__(self):
        return self.ocudescription

    class Meta:
        managed = True
        db_table = 'occupation'


class OccupationLanguage(models.Model):
    oclcode = models.AutoField(primary_key=True)
    oclname = models.CharField(max_length=100)
    ocucode = models.ForeignKey(Occupation, models.DO_NOTHING,
                                db_column='ocucode',
                                related_name='occupationlang_occupation')
    lancode = models.ForeignKey(Language, models.DO_NOTHING,
                                db_column='lancode',
                                related_name='occupationlang_language')

    def __str__(self):
        return self.oclname

    class Meta:
        managed = True
        db_table = 'occupation_language'


class TypeClient(models.Model):
    tclcode = models.AutoField(primary_key=True)
    tcldescription = models.CharField(max_length=30)
    tclactive = models.BooleanField()

    def __str__(self):
        return self.tcldescription

    class Meta:
        managed = True
        db_table = 'typeclient'


class Pet(models.Model):
    petcode = models.AutoField(primary_key=True)

dateSite/models/credits.py
import json
import os.path
from django.db import models
from .client import Client, PhotoAlbum, ClientCollectionAlbum
from .purchase import Purchase
from .service import SubService

def purch_album(request, album_added):
    client = Client.objects.get(clicode=request.user.pk)
    album = PhotoAlbum.objects.get(phacode=album_added)
    member_album = Client.objects.get(clicode=album.clicode_id)

    collection = ClientCollectionAlbum.objects.filter(
        clicode=client,
        phacode=album)

    if not collection.exists():
        collection = ClientCollectionAlbum()
        collection.clicode = client
        collection.phacode = album
        collection.save()

    clisender = client.as_dict()
    clireciever = member_album.as_dict()
    data = {}
    data["clisender"] = clisender
    data["clireciever"] = clireciever
    return json.dumps(data)

dateSite/models/deniedip.py
from django.db import models

class DeniedIp(models.Model):
    dipcode = models.AutoField(primary_key=True)
    diprange = models.CharField(max_length=25)
    dipactive = models.BooleanField('Active', default=True, null=False, blank=False) 

    def __str__(self):
        return self.diprange

    class Meta:
        managed = True
        db_table = 'deniedip'

dateSite/templates/dateSite/navbar/alerts_menu.html
{% load static from staticfiles %}
{% load sass_tags %}
{% load i18n %}
{% load crispy_forms_tags %}
<div class="row alert-header">
    <div class="col-xs-2 col-sm-4">
        <img src="{% static 'dateSite/img/icons/bell-icon.png' %}" class="icon"/>
        <label class="title hidden-sm-down">ALERTS</label>
    </div>
    <div class="col-xs-10 col-sm-8"><div class="vr"></div></div>
</div>
{% if not verified or not notifications %}
    <p class="no_alerts">No alerts to show</p>
{% else %}
    <div id="notifications">
    {% for alert in notifications  %}
        <div class="notification row">
            <div class="col-xs-3 alert-pic-preview">
                <a href="{% url 'dateSite:profile' slug=alert.clicodesent %}" title="Edit my profile" data-toggle="tooltip">
                    <img src="{%if alert.clicodesent.profile_picture %} {{ alert.clicodesent.profile_picture }} {% else %}{% static 'dateSite/img/default_profile.png' %}{% endif %}"/>
                </a>
            </div>
            <div class="col-xs-9 description">
                @{{ alert.ntymessage }}
                <span class="date">{{ alert.notdate }}</span>
            </div>
        </div>
    {% endfor %}
    </div>
    <div class="col-xs-12 see-all">
        <a href="{% url 'dateSite:alert' %}">See all</a>
    </div>
{% endif %}

dateSite/templates/dateSite/navbar/alerts_menu_home.html
{% load static from staticfiles %}
{% load sass_tags %}
{% load i18n %}
{% load crispy_forms_tags %}

<div name="mnu-window" class="win-alert" style="display:none;">
    <div class="alert-header">
        <img src="{% static 'dateSite/img/icons/bell-icon-gray.png' %}"/>
        <label class="title">ALERT</label>
        <hr />
    </div>
    <div class="alert-content">
    {% if not verified or not notifications %}
        <p class="no_alerts">No alerts to show</p>
    {% else %}
        <ul class="notifications-list">
            {% for alert in notifications  %}
            <a href="/{{alert.clicodesent}}">
            <li class="notification {%if not alert.notread%}not-read{%endif%}" data-user="{{ alert.clicodesent.cliusername }}">
                <div class="prof-img">
                    {% if not alert.clicodesent.profile_picture %}
                    <img src="{% static 'dateSite/img/default.png' %}" alt="{{ alert.clicodesent.cliusername }}" title="{{ alert.clicodesent.cliusername }}"/>
                    {% else %}
                    <img src="{{ alert.clicodesent.profile_picture }}" alt="{{ alert.clicodesent.cliusername }}" title="{{ alert.clicodesent.cliusername }}"/>
                    {% endif %}
                </div>
                <div class="description">
                    <span class="type">@{{ alert.ntymessage }}</span>
                    <span class="date">{{ alert.notdate }}</span>
                </div>
            </li>
            {% endfor %}
        </ul>
    {% endif %}
    </div>
    <div class="alert-footer">
        <a href="{% url 'dateSite:alert' %}">See all</a>
    </div>
</div>

dateSite/templates/dateSite/navbar/profile_menu.html
{% load static from staticfiles %}
{% load sass_tags %}
{% load i18n %}


<div class="profile-header">
{% if verified %}
    <a href="{% url 'dateSite:edit_profile' slug=user.username %}" title="Edit my profile" data-toggle="tooltip">
        <img src="{% static 'dateSite/img/icons/edit.png' %}" alt=""/>
    </a>
{% else %}
    <a href="#" data-toggle="modal" data-target="#verifiedModal">
        <img src="{% static 'dateSite/img/icons/edit.png' %}" />
    </a>
{% endif %}
    <label class="title hidden-sm-down">PROFILE</label>
    <div class="vr"></div>
</div>
<div class="profile-area">
{% if verified %}
    <div id="profile-pic-container" class="profile-pic-container">
        <a href="{% url 'dateSite:profile' slug=user.username %}">
        {% if profile_picture %}
            <img id="dropmenu-profile-pic" src="{{ profile_picture }}" class="img-thumb" alt="@{{ username }}" title="@{{ username }}"/>
        {% else %}
            <img src="{% static 'dateSite/img/default_profile.png' %}" class="img-thumb" alt="@{{ username }}" title="@{{ username }}"/>
        {% endif %}
        </a>
        <div class="save-img"></div>
        <form id="update-profile-menu" class="edit" method="POST" enctype="multipart/form-data" title="Update my profile picture">
            {% csrf_token %} {{ upload_profile_menu }}
        </form>
            {% include 'dateSite/upload_template.html' %}
    </div>
    <div class="basic-info">
        <label class="center">
            <a href="{% url 'dateSite:profile' slug=user.username %}">
                <b>@{{ username }}</b>
            </a><br/>
            {% if name %}
            <b>{{ name }}</b>
            {% endif %}
        </label>
        {% if city %}
        <label>
            <img src="{% static 'dateSite/img/icons/location.png' %}" class="small-icon" /> <i>{{ city }}</i>
        </label>
        {% endif %}
        {% if marital_status %}
        <label>
            <img src="{% static 'dateSite/img/icons/status-icon.png' %}" class="small-icon" />
            {{ marital_status }}
        </label>
        {% endif %}
        {% if height %}
            <label><img src="{% static 'dateSite/img/icons/height-icon.png' %}" class="small-icon" />{{ height }}</label>
        {% endif %}
    </div>
    <a href="{% url 'dateSite:edit_profile' slug=user.username %}" title="Edit my profile" data-toggle="tooltip" class="edit">
        <img src="{% static 'dateSite/img/icons/edit-gray.png' %}" class="edit-icon" title="Edit my profile" data-toggle="tooltip"/>
    </a>
{% else %}
    <div class="profile-pic-container">
        <img src="{% static 'dateSite/img/default_profile.png' %}" class="img-thumb"/>
    </div>
    <div class="basic-info not-verified">
        <b>@{{ user }}</b>
    </div>
{% endif %}
</div>
{% if verified %}
    <div class="action-area">
        <div class="option-icon">
            <a href="{% url 'dateSite:profile' slug=user.username %}">
                <img src="{% static 'dateSite/img/icons/profile-gray.png' %}" alt="View my profile" class="icon" />
                <span class="text">Profile</span>
            </a>
        </div>
        <div class="option-icon">
            <div id="count_inbox" class="alert-count">{{ new_inbox }}</div>
            <a href="{% url 'dateSite:myinbox' %}">
                <img src="{% static 'dateSite/img/icons/inbox.png' %}" alt="Inbox" class="icon" />
                <span class="text">Inbox</span>
            </a>
        </div>
    </div>
{% endif %}
<div class="logout-area">
    <form method="post" action="{% url 'account_logout' %}" id="profile">
        {% csrf_token %}
        <button class="btn btn-outline btn-xs">Log Out</button>
    </form>
</div>

dateSite/templates/dateSite/navbar/profile_menu_home.html
{% load static from staticfiles %}
{% load sass_tags %}
{% load i18n %}

<div name="mnu-window" class="win-profile" style="display:none;">
    <div class="profile-header">
        <img src="{% static 'dateSite/img/icons/edit.png' %}"/>
        <label class="title">PROFILE</label>
        <hr />
    </div>
    <div class="profile-area">
        {% if verified %}
            <div id="profile-pic-container" class="profile-pic-container">
                <a href="{% url 'dateSite:profile' slug=user.username %}">
                {% if profile_picture %}
                    <img id="dropmenu-profile-pic" src="{{ profile_picture }}" class="img-thumb" alt="@{{ username }}" title="@{{ username }}"/>
                {% else %}
                    <img src="{% static 'dateSite/img/default.png' %}" class="img-thumb" alt="@{{ username }}" title="@{{ username }}"/>
                {% endif %}
                </a>
                <div class="save-img"></div>
                <form id="update-profile-menu" class="edit" method="POST" enctype="multipart/form-data" title="Update my profile picture">
                    {% csrf_token %} {{ upload_profile_menu }}
                </form>
                    {% include 'dateSite/upload_template.html' %}
            </div>
            <div class="basic-info">
                <label class="center">
                    <a href="{% url 'dateSite:profile' slug=user.username %}">
                        <b>@{{ username }}</b>
                    </a><br/>
                    {% if name %}
                    <b>{{ name }}</b>
                    {% endif %}
                </label>
                {% if city %}
                <label>
                    <img src="{% static 'dateSite/img/icons/location.png' %}" class="small-icon" /> <i>{{ city }}</i>
                </label>
                {% endif %}
                {% if marital_status %}
                <label>
                    <img src="{% static 'dateSite/img/icons/status-icon.png' %}" class="small-icon" />
                    {{ marital_status }}
                </label>
                {% endif %}
                {% if height %}
                    <label><img src="{% static 'dateSite/img/icons/height-icon.png' %}" class="small-icon" />{{ height }}</label>
                {% endif %}
            </div>
            <a href="{% url 'dateSite:edit_profile' slug=user.username %}" title="Edit my profile" data-toggle="tooltip" class="edit">
                <img src="{% static 'dateSite/img/icons/edit-gray.png' %}" class="edit-icon" title="Edit my profile" data-toggle="tooltip"/>
            </a>
        {% else %}
            <div class="profile-pic-container">
                <img src="{% static 'dateSite/img/default_profile.png' %}" class="img-thumb"/>
            </div>
            <div class="basic-info not-verified">
                <b>@{{ user }}</b>
            </div>
        {% endif %}
    </div>
    {% if verified %}
        <ul class="action-area">
            <li>
                {% if premium_member %}
                <div class="opt-premium"></div>
                <span class="option">PREMIUM MEMBER</span>
                {% else %}
                <a href="https://api.ccbill.com/wap-frontflex/flexforms/f34c27b0-2f5d-4a13-b382-2e04ba89f104?client={{username}}" class="upgradePremiumModal" target="_blank"><div class="opt-upgrade"></div></a>
                <span class="option">UPGRADE TO PREMIUM</span>
                {% endif %}
            </li>
        </ul>
    {% endif %}
    <div class="logout-area">
        <form method="post" action="{% url 'account_logout' %}" id="profile">
            {% csrf_token %}
            <button class="btn btn-outline btn-xs">Log Out</button>
        </form>
    </div>
</div>

dateSite/templates/dateSite/navbar/search_form_home.html
{% load static from staticfiles %}
{% load sass_tags %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load extra_filters %}

<input type="hidden" id="ids" name="ids" value="{{members.0|concat_ids}}" />
<input type="hidden" id="show_more" name="show_more" value="{{members.1}}" />
<input type="hidden" id="id_seaminage" name="minage" value="{{seaminage}}" />
<input type="hidden" id="id_seamaxage" name="maxage" value="{{seamaxage}}" />
<input type="hidden" id="id_gencode" name="id_gencode" value="" />
<input type="hidden" id="id_seacountry" name="coucode" value="{{country}}" />

<div name="mnu-window" class="win-search" style="display:none;">
    <div class="search-header">
        <img src="{% static 'dateSite/img/icons/search-icon-gray.png' %}" />
        <label class="title">SEARCH</label>
        <hr />
    </div>
    <form id="search" method="post" action="{% url 'dateSite:main' %}" class="search-content">
        {% csrf_token %}
        {% crispy search_form %}
        <input type="submit" class="search-btn btn btn-primary btn-xs" value="SEARCH" />
    </form>
</div>